-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\wahWahEffect\Fc.vhd
-- Created: 2023-04-17 20:14:47
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Fc
-- Source Path: wahWahEffect/wahWahEffectSystem/stateVariableFilter/Fc
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Fc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        minf                              :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        maxf                              :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        delta                             :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        fc_1                              :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En16
        );
END Fc;


ARCHITECTURE rtl OF Fc IS

  ATTRIBUTE multstyle : string;

  -- Signals
  SIGNAL maxf_unsigned                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL minf_unsigned                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL delta_unsigned                   : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL Add2_uminus_cast                 : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Add2_uminus_cast_1               : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Add2_uminus_cast_2               : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL Add2_out1                        : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL delta_dtc                        : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Delay1_out1                      : std_logic;
  SIGNAL Logical_Operator_out1            : std_logic;
  SIGNAL Switch1_out1                     : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Add1_out1                        : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL Relational_Operator1_1_cast      : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL Relational_Operator1_relop1      : std_logic;
  SIGNAL Switch_out1                      : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Add_out1                         : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL Delay_out1                       : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL Add_add_cast                     : signed(34 DOWNTO 0);  -- sfix35_En16
  SIGNAL Add_add_cast_1                   : signed(34 DOWNTO 0);  -- sfix35_En16
  SIGNAL Add_add_temp                     : signed(34 DOWNTO 0);  -- sfix35_En16
  SIGNAL Add1_add_cast                    : signed(34 DOWNTO 0);  -- sfix35_En16
  SIGNAL Add1_add_cast_1                  : signed(34 DOWNTO 0);  -- sfix35_En16
  SIGNAL Add1_add_temp                    : signed(34 DOWNTO 0);  -- sfix35_En16

BEGIN
  -- 					FC
  -- 
  -- Creat a Triangular Wave 
  -- 
  -- Minimum Frequency --> Maximum Frequency
  -- 
  -- Maximum Frequency --> Minimum Frequency

  maxf_unsigned <= unsigned(maxf);

  minf_unsigned <= unsigned(minf);

  delta_unsigned <= unsigned(delta);

  Add2_uminus_cast <= signed(resize(delta_unsigned, 17));
  Add2_uminus_cast_1 <= resize(Add2_uminus_cast, 18);
  Add2_uminus_cast_2 <=  - (Add2_uminus_cast_1);
  Add2_out1 <= Add2_uminus_cast_2(16 DOWNTO 0);

  delta_dtc <= signed(resize(delta_unsigned, 17));

  Logical_Operator_out1 <=  NOT Delay1_out1;

  
  Switch1_out1 <= maxf_unsigned WHEN Logical_Operator_out1 = '0' ELSE
      minf_unsigned;

  Relational_Operator1_1_cast <= signed(resize(Switch1_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  
  Relational_Operator1_relop1 <= '1' WHEN Add1_out1 < Relational_Operator1_1_cast ELSE
      '0';

  Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        Delay1_out1 <= Relational_Operator1_relop1;
      END IF;
    END IF;
  END PROCESS Delay1_process;


  
  Switch_out1 <= Add2_out1 WHEN Delay1_out1 = '0' ELSE
      delta_dtc;

  Delay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Delay_out1 <= to_signed(0, 34);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_2048_0 = '1' THEN
        Delay_out1 <= Add_out1;
      END IF;
    END IF;
  END PROCESS Delay_process;


  Add_add_cast <= resize(Delay_out1, 35);
  Add_add_cast_1 <= resize(Switch_out1, 35);
  Add_add_temp <= Add_add_cast + Add_add_cast_1;
  
  Add_out1 <= "0111111111111111111111111111111111" WHEN (Add_add_temp(34) = '0') AND (Add_add_temp(33) /= '0') ELSE
      "1000000000000000000000000000000000" WHEN (Add_add_temp(34) = '1') AND (Add_add_temp(33) /= '1') ELSE
      Add_add_temp(33 DOWNTO 0);

  Add1_add_cast <= resize(Add_out1, 35);
  Add1_add_cast_1 <= signed(resize(minf_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 35));
  Add1_add_temp <= Add1_add_cast + Add1_add_cast_1;
  
  Add1_out1 <= "0111111111111111111111111111111111" WHEN (Add1_add_temp(34) = '0') AND (Add1_add_temp(33) /= '0') ELSE
      "1000000000000000000000000000000000" WHEN (Add1_add_temp(34) = '1') AND (Add1_add_temp(33) /= '1') ELSE
      Add1_add_temp(33 DOWNTO 0);

  fc_1 <= std_logic_vector(Add1_out1);

END rtl;

