-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\wahWahEffect\Q1.vhd
-- Created: 2023-04-17 20:14:47
-- 
-- Generated by MATLAB 9.13 and HDL Coder 4.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Q1
-- Source Path: wahWahEffect/wahWahEffectSystem/stateVariableFilter/Q1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Q1 IS
  PORT( damp                              :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En16
        q1_1                              :   OUT   std_logic_vector(17 DOWNTO 0)  -- ufix18_En16
        );
END Q1;


ARCHITECTURE rtl OF Q1 IS

  -- Signals
  SIGNAL damp_unsigned                    : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL Constant_out1                    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Product2_out1                    : unsigned(17 DOWNTO 0);  -- ufix18_En16

  ATTRIBUTE multstyle : string;

BEGIN
  -- 				
  -- 	Tuning Coefficient Q1
  -- 
  -- 		Q1 = 2*d

  damp_unsigned <= unsigned(damp);

  Constant_out1 <= to_unsigned(16#2#, 2);

  Product2_out1 <= damp_unsigned * Constant_out1;

  q1_1 <= std_logic_vector(Product2_out1);

END rtl;

